config/routes.rb
Rails.application.routes.draw do
  get 'careers/ruby'

  get 'careers/ruby_f'

  get 'careers/postgress'

  get 'careers/postgress_f'

  get 'careers/director'

  get 'careers/director_f'

  get 'careers/sme'

  get 'careers/sme_f'

  get 'careers/consumer'

  get 'careers/consumer_f'

  get 'careers/index'

  get 'home/about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "home#index"
  resources :contact_details
  resources :feedbacks

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact_detail.rb
class ContactDetail < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  validates :full_name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true


end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  validates :email_address, :email => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController

 layout 'careers'
  def ruby
  end

  def ruby_f
  end

  def postgress
  end

  def postgress_f
  end

  def director
  end

  def director_f
  end

  def sme
  end

  def sme_f
  end

  def consumer
  end

  def consumer_f
  end

  def index
   render :layout => false
  end
end

app/controllers/contact_details_controller.rb
class ContactDetailsController < ApplicationController

  before_filter :authenticate_admin_user! , except: :new

  def index
    @contact_details = ContactDetail.all
  end


  def new
    @contact_detail = ContactDetail.new
  end


  def create
    @contact_detail = ContactDetail.new(contact_detail_params)

    respond_to do |format|
      if @contact_detail.save
        format.html { redirect_to careers_index_path, notice: 'Contact detail was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end



  private
  def contact_detail_params
    params.require(:contact_detail).permit(:full_name, :email, :phone_number, :attachment)
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def new
    @feedback = Feedback.new
  end


  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to root_path, notice: 'Feedback was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  private

  def feedback_params
    params.require(:feedback).permit(:email_address)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/careers/consumer.html.erb
<div class="c_head_background">
  <div class="c_head_div">
    <p class="c_head">Product Manager – “Ideaz” – the home design channel</p>
    <p class="c_head1"> Wellington, Development, Full-time</p>
    <%= link_to "APPLY NOW", careers_consumer_f_path, class:"button_a  head_b" %>
  </div>



  <div class="body_div" >
  <p class="c_subhead">Job brief</p>

    <p>We are looking for a product manager to work closely with design and engineering to help build and award winning experience for our desktop/mobile users.</p>

    <br>
    <p  class="c_subhead">Position Responsibilities:</p>

    <ul class="myul">
      <li><span>	Work collaboratively with design/engineering to deliver the best experience for home renovation and design on mobile and tablet devices</span></li>
      <li><span>    Help develop, manage and communicate the desktop and mobile product roadmap</span></li>
      <li><span>	Define and analyse product metrics to inform decision-making and measure success</span></li>
      <li><span>	Leverage user research, feedback, and usability studies to inform new areas of product growth</span></li>
      <li><span>	Clearly articulate product strategy and benefits to a wide range of people, internal and external</span></li>
      <li><span>	Stay up to date on the latest mobile developments and come up with new ways to delight Ideaz users</span></li>
    </ul>



    <br>

    <p  class="c_subhead">Desired Skills & Experience:</p>

    <ul class="myul">
      <li><span>	Software Engineering background required (CS degree and/or coding experience)</span></li>
      <li><span>	4+ years of experience with product management, with at least 2 years of experience developing and delivering mobile products</span></li>
      <li><span>	Have a clear track record of shipping successful mobile products on iOS and Android, specifically applications that already have large and rapidly-growing user bases</span></li>
      <li><span>	Have the ability to manage projects across varying technology stacks and can understand deep technical issues that arise from both</span></li>
      <li><span>	Have technical independence: can quickly collect and analyse data from a variety of environments without help from others</span></li>
      <li><span>	Must care deeply about user experience and have strong consumer product instincts</span></li>
      <li><span>	Extremely detail-oriented and organised, with the ability to manage many projects in parallel</span></li>
      <li><span>	Excellent written and verbal communication skills</span></li>
      <li><span>	Background in mobile ecommerce or social media is a plus</span></li>
    </ul>
    <br>
    <P>Interested? Send us your resume below and we will be in contact.</P>

    <br>
    <br>
    <br>
    <br>
    <%= link_to "APPLY NOW", careers_ruby_f_path, class: "button_a foot_b" %>
    <br>
    <br>
    <br>
    <br>
    <%= link_to "Go back to carrers page", careers_index_path, class: "go_back" %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/careers/consumer_f.html.erb
<h1>Careers#consumer_f</h1>
<p>Find me in app/views/careers/consumer_f.html.erb</p>


<%= render :partial => "contact_details/new", :locals => {:contact_detail => ContactDetail.new} %>

app/views/careers/director.html.erb
<div class="c_head_background">
  <div class="c_head_div">
    <p class="c_head"> Operations Director/COO designate</p>
    <p class="c_head1"> Wellington, Development, Full-time</p>
    <%= link_to "APPLY NOW", careers_director_f_path, class:"button_a  head_b" %>
  </div>

  <div class="body_div" >
    <p class="c_subhead">Job brief</p>

    <p>Love efficient processes, controls, rolling your sleeves up and building something special?</p>
<br>
    <p>This is a unique role that will see you oversee the preparation and execution of part the strategic vision as well as lead the day to day operations of this innovative online business.</p>
    <p>You will work to provide innovation and inspiration to your key reports so that all the business functions work in harmony.</p>

    <br>
    <p  class="c_subhead">You will be responsible for:</p>

    <ul class="myul">
      <li><span>Designing and implementing specific business processes for HR, finance, Customer support and sales support</span></li>
      <li><span>Ensuring department operations are efficient and achieving optimal outcomes.</span></li>
      <li><span>Establishing clear financial and operational controls.</span></li>
   </ul>

    <br>

    <p  class="c_subhead">Requirements</p>

    <ul class="myul">
      <li><span>The successful candidate will demonstrate a broad range of skills and leadership traits achieved within an online/subscription based environment.</span></li>
      <li><span> You will have an exceptional track record as a business leader in an executive position in an innovative/online business. </span></li>
      <li><span>Your ability to prioritise and organise will be excellent as will your ability to motivate and energise your teams and key stakeholders.</span></li>
      <li><span> With an influential personality you will showcase leadership, responsibility, creativity and inspired decision making.</span></li>
      <li><span> A background working with in an online business would be highly regarded.</span></li>
    </ul>
    <br>
    <P>Interested? Send us your resume below and we will be in contact.</P>

    <br>
    <br>
    <br>
    <br>
    <%= link_to "APPLY NOW", careers_ruby_f_path, class: "button_a foot_b" %>
    <br>
    <br>
    <br>
    <br>
    <%= link_to "Go back to carrers page", careers_index_path, class: "go_back" %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/careers/director_f.html.erb
<h1>Careers#director_f</h1>
<p>Find me in app/views/careers/director_f.html.erb</p>


<%= render :partial => "contact_details/new", :locals => {:contact_detail => ContactDetail.new} %>

app/views/careers/index.html.erb
<h1>Careers</h1>
<br>
<br>
<p>positions you can apply for today</p>
<br>
<br>
<br>
<br>
<p>Ruby on Rails Developer</p>
<li><%= link_to "Apply Now", careers_ruby_path %></li>
<p>Senior PostgresSQL DBA</p>
<li><%= link_to "Apply Now", careers_postgress_path %></li>
<p>Operations Derectors</p>
<li><%= link_to "Apply Now", careers_director_path %></li>
<p>product manager -sme</p>
<li><%= link_to "Apply Now", careers_sme_path %></li>
<p>product manager -consumer</p>
<li><%= link_to "Apply Now", careers_consumer_path %></li>

app/views/careers/postgress.html.erb
<div class="c_head_background">
  <div class="c_head_div">
    <p class="c_head"> Senior PostgreSQL DBA </p>
    <p class="c_head1"> Wellington, Development, Full-time</p>
    <%= link_to "APPLY NOW", careers_postgress_f_path, class:"button_a  head_b" %>
  </div>


  <div class="body_div" >
    <p class="c_subhead">Job brief</p>

    <p>Are you a PostgreSQL guru? Love data?  We are seeking an experienced DBA to help build and maintain our highly scalable database systems.</p>

    <br>
    <p  class="c_subhead">What will you do?</p>

    <ul class="myul">
      <li ><span>Design infrastructure and systems to support high volume database systems</span></li>
      <li ><span>Forecast and plan for the infrastructure needs of a rapidly growing SaaS company</span></li>
      <li ><span>Collaborate with our world class engineering team to detect and resolve infrastructure problems</span></li>
      <li ><span>Maintain redundant and secure database systems</span></li>
    </ul>
    <br>
    <br>
    <p>The position is a hands-on position responsible for configuring, integrating, and maintaining all the companies Development, Staging and Production PostgreSQL databases.</p>

    <p>The position also includes monitoring databases to optimize database performance and diagnosing any issues.</p>

    <p>The DBA will also help develop, implement, maintain policies and procedures and document database architecture to ensure the security and integrity of the databases. They will implement data models, database designs, data access, table maintenance and code changes together with our development team. The DBA will work towards excellence and actively participate in the continual improvement of the department and company.</p>

    <br>
    <p  class="c_subhead">Requirements</p>

        <ul class="myul">
          <li><span> 3-6 years of administering large PostgreSQL databases</span></li>
          <li><span> Must have the ability to do performance tuning / index maintenance to meet and assist the needs of the Development teams using PostgreSQL</span></li>
          <li><span>Must have experience backing up and restoring PostgreSQL database on a regular basis</span></li>
          <li><span>Designing and Managing PostgreSQL database schemas</span></li>
          <ul>
              <li><span>Experience in Security access control</span></li>
              <li><span>Experience with testing</span></li>
              <li><span>Experience with configuration management</span></li>
              <li><span>Experience with version control</span></li>
              <li><span>Experience with 24x7 zero downtime database management</span></li>
              <li><span>Knowledge of fault detection and resolution processes</span></li>
          </ul>
        </ul>
    <br>
    <P>Interested? Send us your resume below and we will be in contact.</P>

    <br>
    <br>
    <br>
    <br>
    <%= link_to "APPLY NOW", careers_ruby_f_path, class: "button_a foot_b" %>
    <br>
    <br>
    <br>
    <br>
    <%= link_to "Go back to carrers page", careers_index_path, class: "go_back" %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/careers/postgress_f.html.erb
<h1>Careers#postgress_f</h1>
<p>Find me in app/views/careers/postgress_f.html.erb</p>


<%= render :partial => "contact_details/new", :locals => {:contact_detail => ContactDetail.new} %>

app/views/careers/ruby.html.erb
<div class="c_head_background">
  <div class="c_head_div">
    <p class="c_head"> Ruby on rails developer</p>
    <p class="c_head1"> Wellington, Development, Full-time</p>
<%= link_to "APPLY NOW", careers_ruby_f_path, class:"button_a  head_b" %>
  </div>


<div class="body_div" >
<p class="c_subhead">Job brief</p>

<p>Do you like writing mean and clean Ruby code?</p>

<p>We’re looking for 2 people with a passion for programming and for writing beautiful code.  You will be part of a team building an exceptional product.</p>

  <br>
<p  class="c_subhead">Responsibilities</p>

  <ul class="myul">
    <li ><span>Write clean, maintainable and efficient code</span></li>
    <li ><span>Design robust, scalable and secure features</span></li>
    <li ><span>Contribute in all phases of the development lifecycle</span></li>
    <li ><span>Follow best practices (test-driven development, continuous integration, SCRUM, refactoring, code standards)</span></li>
    <li ><span>Drive continuous adoption and integration of relevant new technologies into design</span></li>
  </ul>


  <br>

  <p  class="c_subhead">Requirements</p>

  <ul class="myul">
    <li><span> Relevant degree in Computer Science, Engineering or a related subject</span></li>
    <li><span>Proven working experience in developing applications with Ruby on Rails </span></li>
    <li><span>  Proven working experience in software development</span></li>
    <li><span>Demonstrable knowledge of front-end technologies such as JavaScript, HTML, CSS & JSON </span></li>
    <li><span>Experience developing highly interactive applications </span></li>
    <li><span>  A firm grasp of object oriented analysis and design</span></li>
    <li><span> Passion for writing great, simple, clean, efficient code</span></li>
    <li><span> Good knowledge of relational databases</span></li>
    <li><span> Working knowledge of PostgreSQL</span></li>
  </ul>

</div>
</div>

app/views/careers/ruby_f.html.erb
<div class="c_head_background">
  <div class="c_head_div">
    <p class="c_head"> Ruby on rails developer</p>
    <p class="c_head1"> Wellington, Development, Full-time</p>
  </div>
  <div class="body_div" >

<%= render :partial => "contact_details/new", :locals => {:contact_detail => ContactDetail.new} %>



<%= link_to "Go back to carrers page", careers_index_path, class: "go_back" %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/careers/sme.html.erb
<div class="c_head_background">
  <div class="c_head_div">
    <p class="c_head"> Product Manager – “Homes – find yours”</p>
    <p class="c_head1"> Wellington, Development, Full-time</p>
    <%= link_to "APPLY NOW",  careers_sme_f_path , class:"button_a  head_b" %>
  </div>

  <div class="body_div" >
    <p class="c_subhead">Job brief</p>
    <p>We are looking for a product manager to work closely with design and engineering to help build and award winning experience for our desktop/mobile users.</p>

    <br>
    <p  class="c_subhead">Position Responsibilities:</p>


    <ul class="myul">
      <li><span>    Work collaboratively with design/engineering to deliver the best experience for home owners and hunters on mobile and tablet devices</span></li>
      <li><span>	Help develop, manage and communicate the desktop and mobile product roadmap</span></li>
      <li><span>	Define and analyse product metrics to inform decision-making and measure success</span></li>
      <li><span>	Leverage user research, feedback, and usability studies to inform new areas of product growth</span></li>
      <li><span>	Clearly articulate product strategy and benefits to a wide range of people, internal and external</span></li>
      <li><span>	Stay up to date on the latest mobile developments and come up with new ways to delight Ideaz users</span></li>
   </ul>


    <br>

    <p  class="c_subhead">Desired Skills & Experience:</p>

    <ul class="myul">
      <li><span>	Software Engineering background required (CS degree and/or coding experience)</span></li>
      <li><span>	4+ years of experience with product management, with at least 2 years of experience developing and delivering mobile products</span></li>
      <li><span>	Have a clear track record of shipping successful mobile products on iOS and Android, specifically applications that already have large and rapidly-growing user bases</span></li>
      <li><span>	Have the ability to manage projects across varying technology stacks and can understand deep technical issues that arise from both</span></li>
      <li><span>	Have technical independence: can quickly collect and analyse data from a variety of environments without help from others</span></li>
      <li><span>	Must care deeply about user experience and have strong consumer product instincts</span></li>
      <li><span>	Extremely detail-oriented and organised, with the ability to manage many projects in parallel</span></li>
      <li><span>	Excellent written and verbal communication skills</span></li>
      <li><span>	Background in mobile ecommerce or social media is a plus</span></li>
    </ul>
    <br>
    <P>Interested? Send us your resume below and we will be in contact.</P>

    <br>
    <br>
    <br>
    <br>
    <%= link_to "APPLY NOW", careers_ruby_f_path, class: "button_a foot_b" %>
    <br>
    <br>
    <br>
    <br>
    <%= link_to "Go back to carrers page", careers_index_path, class: "go_back" %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/careers/sme_f.html.erb
<h1>Careers#sme_f</h1>
<p>Find me in app/views/careers/sme_f.html.erb</p>


<%= render :partial => "contact_details/new", :locals => {:contact_detail => ContactDetail.new} %>

app/views/contact_details/_new.html.erb
<h1>Contact Detail</h1>

<%= form_for(contact_detail, html: { multipart: true } ) do |f| %>
    <% if contact_detail.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(contact_detail.errors.count, "error") %> prohibited this contact_detail from being saved:</h2>

          <ul>
            <% contact_detail.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :full_name %><br>
      <%= f.text_field :full_name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :phone_number %><br>
      <%= f.text_field :phone_number %>
    </div>
    <br>
    <div class="field">
      <%= f.label :attachment %><br>
      <%= f.file_field :attachment %>
    </div>
    <br>
    <br>
    <br>
    <div >
      <%= f.submit "SUBMIT APPLICATION", class: "button_a foot_b" %>
    </div>
    <br>

<% end %>

app/views/contact_details/index.html.erb
<h1>All contact details</h1>

<table>
  <thead>
  <tr>
    <th>Full name</th>
    <th>Attachment</th>

  </tr>
  </thead>

  <tbody>
  <% @contact_details.each do |contact_detail| %>
      <tr>
        <td><%= contact_detail.full_name %></td>

        <td><%= link_to "Download Resume", contact_detail.attachment_url %></td>

      </tr>
  <% end %>
  </tbody>
</table>


app/views/feedbacks/_new.html.erb
<%= form_for(feedback) do |f| %>

    <div class="field">
      <%= f.label :email_address %><br>
      <%= f.text_field :email_address %>
    </div>
    <div class="actions">
      <%= f.submit "Go" %>
    </div>
<% end %>

app/views/home/about.html.erb
<h1>About Us</h1>
<br>
<br>
<p>Our Story</p>

app/views/home/index.html.erb
<p> Explore Every Home in New zealand</p>

<%= render :partial => "contact_details/new", :locals => {:contact_detail => ContactDetail.new} %>
<br>
<br>
<%= render :partial => "feedbacks/new", :locals => {:feedback => Feedback.new} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carrer2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body >
<div class= "width" >
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "About",  home_about_path %></li>
  <li><%= link_to "Careers",  careers_index_path %></li>
  <br>
  <li><%= link_to "Now Hiring",  careers_index_path %></li>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/careers.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carrer2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body >
<%= yield %>



</body>
</html>